"""initial 15 tables

Revision ID: 661775409e7f
Revises: 
Create Date: 2026-08-05 10:28:51.925166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '661775409e7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_templates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='量表名'),
    sa.Column('category', sa.String(length=32), nullable=True, comment='分类'),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='满分'),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='分项字段定义'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='如 PT大厅 / PT-1室'),
    sa.Column('room_type', sa.String(length=10), nullable=False, comment='PT/OT/ST'),
    sa.Column('capacity', sa.Integer(), server_default='1', nullable=False, comment='容量（容量管理 TBD）'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("room_type IN ('PT','OT','ST')", name='ck_rooms_room_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='patient/therapist/doctor/admin'),
    sa.Column('display_name', sa.String(length=64), nullable=False, comment='显示名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='可选短信通道'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='禁用标记'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("role IN ('patient','therapist','doctor','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('uk_users_username', ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='操作人'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='如 course.force_replace'),
    sa.Column('entity_type', sa.String(length=32), nullable=False, comment='course/patient/alert…'),
    sa.Column('entity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='变更前后快照'),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True, comment='科室'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='职称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='接收人'),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='模板渲染后文本'),
    sa.Column('link', sa.String(length=255), nullable=True, comment='跳转路由'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('channel', sa.String(length=20), server_default='inbox', nullable=False, comment='inbox/browser/sms'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("channel IN ('inbox','browser','sms')", name='ck_notifications_channel'),
    sa.CheckConstraint("type IN ('course_new','course_change','course_reminder','course_overdue','assessment_todo','alert')", name='ck_notifications_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 表达式索引（autogenerate 无法反射 DESC 索引，手动补充，见 database.md §2.12）
    op.create_index('idx_notifications_user', 'notifications',
                    ['user_id', 'is_read', sa.text('created_at DESC')], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='SHA-256'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_user', ['user_id'], unique=False)

    op.create_table('therapists',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=10), nullable=False, comment='PT/OT/ST'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='职称'),
    sa.Column('certified', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='资质审核'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("group_name IN ('PT','OT','ST')", name='ck_therapists_group_name'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='登录账号'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='男/女'),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True, comment='诊断'),
    sa.Column('admission_date', sa.Date(), nullable=True, comment='入院日期'),
    sa.Column('ward_location', sa.String(length=128), nullable=True, comment='病房位置（如 住院部3楼5床）'),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='主管医生'),
    sa.Column('therapist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='责任康复师'),
    sa.Column('status', sa.String(length=20), server_default='ward', nullable=False, comment='患者状态枚举（冗余列，与 patient_status_log 双写，见裁决-5）'),
    sa.Column('external_patient_no', sa.String(length=64), nullable=True, comment='HIS 患者号（备用冗余，不参与业务逻辑，architecture.md §9.4）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("status IN ('ward','en_route','treating','paused','absent','discharged')", name='ck_patients_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patients_doctor_id', ['doctor_id'], unique=False)
        batch_op.create_index('idx_patients_status', ['status'], unique=False)
        batch_op.create_index('idx_patients_therapist_id', ['therapist_id'], unique=False)

    op.create_table('therapist_shifts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('therapist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False, comment='scheduled/on_duty/absent/leave'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("status IN ('scheduled','on_duty','absent','leave')", name='ck_therapist_shifts_status'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('therapist_shifts', schema=None) as batch_op:
        batch_op.create_index('uk_shifts', ['therapist_id', 'work_date'], unique=True)

    op.create_table('assessments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('assess_type', sa.String(length=64), nullable=False, comment='冗余类型名（Fugl-Meyer / Barthel…）'),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True, comment='评分'),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='分项明细'),
    sa.Column('assessor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='评估人（康复师）'),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index('idx_assessments_patient', ['patient_id', 'assessed_at'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('therapist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('room_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('course_type', sa.String(length=10), nullable=False, comment='PT/OT/ST（与 room 类型一致）'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False, comment='计划开始（15min 粒度）'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='计划结束'),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False, comment='课程状态枚举'),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True, comment='实际开始（点开始上课）'),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True, comment='实际结束（点结束上课）'),
    sa.Column('minutes_consumed', sa.Integer(), nullable=True, comment='课时消耗（实际时长，向上取整 15min，TBD）'),
    sa.Column('session_note', sa.Text(), nullable=True, comment='治疗记录'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='排课人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("course_type IN ('PT','OT','ST')", name='ck_courses_course_type'),
    sa.CheckConstraint("status IN ('scheduled','reminded','ongoing','completed','leave','absent','abnormal')", name='ck_courses_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('idx_courses_patient_time', ['patient_id', 'start_at', 'end_at'], unique=False)
        batch_op.create_index('idx_courses_therapist_time', ['therapist_id', 'start_at', 'end_at'], unique=False)

    op.create_table('patient_status_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True, comment='位置快照（如 PT大厅2号床）'),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='触发人'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='course_action/manual_fix/system'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='流转时间'),
    sa.CheckConstraint("source IN ('course_action','manual_fix','system')", name='ck_patient_status_log_source'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 表达式索引（autogenerate 无法反射 DESC 索引，手动补充，见 database.md §2.8）
    op.create_index('idx_patient_status_log_patient', 'patient_status_log',
                    ['patient_id', sa.text('occurred_at DESC')], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('ref_course_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='关联课程'),
    sa.Column('ref_patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='关联患者'),
    sa.Column('summary', sa.String(length=255), nullable=False, comment='摘要'),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False, comment='open/resolved/ignored'),
    sa.Column('resolved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("alert_type IN ('course_overdue','patient_absent','conflict_unresolved')", name='ck_alerts_alert_type'),
    sa.CheckConstraint("status IN ('open','resolved','ignored')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['ref_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['ref_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 表达式索引（autogenerate 无法反射 DESC 索引，手动补充，见 database.md §2.13）
    op.create_index('idx_alerts_status', 'alerts',
                    ['status', sa.text('created_at DESC')], unique=False)
    op.create_table('course_status_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='操作人（系统动作=null）'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='流转时间'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_status_log', schema=None) as batch_op:
        batch_op.create_index('idx_course_status_log_course', ['course_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_status_log', schema=None) as batch_op:
        batch_op.drop_index('idx_course_status_log_course')

    op.drop_table('course_status_log')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_status')

    op.drop_table('alerts')
    with op.batch_alter_table('patient_status_log', schema=None) as batch_op:
        batch_op.drop_index('idx_patient_status_log_patient')

    op.drop_table('patient_status_log')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('idx_courses_therapist_time')
        batch_op.drop_index('idx_courses_patient_time')

    op.drop_table('courses')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index('idx_assessments_patient')

    op.drop_table('assessments')
    with op.batch_alter_table('therapist_shifts', schema=None) as batch_op:
        batch_op.drop_index('uk_shifts')

    op.drop_table('therapist_shifts')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('idx_patients_therapist_id')
        batch_op.drop_index('idx_patients_status')
        batch_op.drop_index('idx_patients_doctor_id')

    op.drop_table('patients')
    op.drop_table('therapists')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_tokens_user')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_user')

    op.drop_table('notifications')
    op.drop_table('doctors')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_log_entity')
        batch_op.drop_index('idx_audit_log_actor')

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uk_users_username')
        batch_op.drop_index('idx_users_role')

    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('assessment_templates')
    # ### end Alembic commands ###
